color= input("What is your favorite color? ")
print("That's cool, your favorite color is", color,"!")
color2= input("If you like another color type it, If you don't just press enter ")
print("So you like"); print(color); print(color2)
print("It's nice to meet you, my favorite color is red!")