
print("Please enter the following information:\n\n")
name= input("First name: ")
lastname= input("Last name: ")
emailadrs= input("Email address: ")
phone= input("Phone number: ")
job= input("Job title: ")
ID= input("ID number: ")
hair_color= input("Hair color: ")
eye_color= input("Eye color: ")
month= input("Month you started: ")
training= input("Advanced training completed(yes/no): ")
print("\n\nThe ID card is: ")
print("----------------------------------------")
print(lastname.upper() + ", " + name.title())
print(job.title())
print("ID: " + ID + "\n")
print(emailadrs.lower())
print(phone)
print("\nHair: " + hair_color + "\tEyes: " + eye_color)
print("\nMonth: " + month + "\tTraining: " + training)
print("----------------------------------------")