print("Please enter the following:\n")
adj= input("adjective: ")
animal= input("animal: ")
verb0=input("verb: ")
exclam= input("exclamation: ")
verb1= input("verb: ")
verb2= input("verb: ")
preposition= input ("preposition: ")
relative= input ("a relative's name: ")
verb3= input("interaction between individuals verb: ")
friend= input("friend name: ")
print("\nYour story is:\n")
print("The other day, I was really in trouble. It all started when I saw a very")
print(adj, animal,  verb0, "down the hallway. " + exclam.capitalize() + "! I yelled. But all")
print("I could think to do was to " + verb1 + " over and over. Miraculously,")
print("that caused it to stop, but not before it tried to " + verb2)
print("right " + preposition + " of my family. The " + adj + animal + " started to " + verb1 + " too")
print("and that made " + relative.capitalize() + " to " + verb3 + " with " + friend.capitalize() + ".")